### ISSUE TITLE
/hack.af command not autosuggested due to period

### ISSUE THREAD

**Issue by maxwofford** [hackclub/hack.af#62]
Slack's slash command autosuggestions show hack.af before I type a period:

<img width="541" alt="Screenshot 2023-09-08 at 11 37 03" src="https://github.com/hackclub/hack.af/assets/5891442/86e07956-1800-49dc-a46c-8a399d62edca">

But after entering the period it disappears:

<img width="308" alt="Screenshot 2023-09-08 at 11 36 58" src="https://github.com/hackclub/hack.af/assets/5891442/77ea6efa-b32e-4978-b32a-c8091c694b9a">

Compare to /z's command, where I know I'm entering a valid command:

<img width="546" alt="Screenshot 2023-09-08 at 11 38 13" src="https://github.com/hackclub/hack.af/assets/5891442/1a1b704a-c4e6-43fa-9e83-a58abb8c314e">

**Comment by DevIos01** [comment]
@grymmy i had bring this at https://github.com/hackclub/hack.af/issues/63 , check the comment on it

**Comment by grymmy** [comment]
I don't see us being able to work around this without just changing the command to /hackaf instead of /hack.af...  given that would also rock the boat, I propose we wontfix this.

If you feel strongly that this is being closed inappropriately and want to fight for this work to be done, please re-open this issue with a comment.
